name: Jib

on:
  push:
    branches:
      - main
      - feature/jib-build-action

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: mvn jib:build
        env:
          CONTAINER_IMAGE: ghcr.io/${{ github.repository }}
        run: |
          mvn -B package jib:build -DskipTests -Djib.to.image=$CONTAINER_IMAGE -Djib.to.tags=latest \
              -Djib.to.auth.username=${{ github.repository_owner }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}

